languageCode = "en-us"
title = "William Young"
baseurl = "https://williamtyoung.github.io"
theme = "black-and-light"
copyright = "William Young"
publishdir = "williamtyoung.github.io"

[Author]
	name = "William Young"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Wait, I have to provide a description!?"
	twitter = "https://twitter.com/code_things"
	github = "https://github.com/williamtyoung"
